### ISSUE TITLE
Attribute conflict with Ohai packages plugin

### ISSUE THREAD

**Issue by jmthomas91** [mattray/packages-cookbook#11]
Both this cookbook and the Ohai packages plugin are trying to use the node["packages"] attribute for different things. Ohai is using it to store package information gleaned from the Node's package system and this cookbook is looking at node["packages"] for packages to install or act upon.

Now that the Ohai plugin is enabled by default by Chef any cookbooks using this cookbook now break on systems where the Ohai packages plugin is installed.

**Comment by mattray** [comment]
Well that's unfortunate, I didn't know this had been enabled by default and that's likely to generate a whole lot of ohai data. The easy solution will be to change the namespace of the attribute we use from 'packages' to something else. 'packages-cookbook'? I'm open to suggestions, I'll rev it in a few days and make it a major version bump.

**Comment by jmthomas91** [comment]
That's what I would suggest too. At the moment as a stopgap workaround I'm inlining the recipe and 'packages-cookbook' is actually exactly how I namespaced the attribute. :P
