### ISSUE TITLE
Push v0.5.0 to community site?

### ISSUE THREAD

**Issue by patcon** [mattray/packages-cookbook#8]
Hey @mattray, mind pushing the new release? Thanks :)

cc: @jtimberman (in case he needs collab access)

**Comment by mattray** [comment]
I tried, apparently I'm no longer the maintainer. @jtimberman if you want to add me back I'll push 0.5.0.

**Comment by jtimberman** [comment]
Weird. I've added you as a collaborator, @mattray.

**Comment by mattray** [comment]
Pushed to SuperMarket.

**Comment by patcon** [comment]
Thanks both of ye!
